language: python
sudo: false
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy
#   - pypy3
#   pending 3.3-compatible release
install:
    - pip install .
    - if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then pip install bcrypt; fi
script:
    - python setup.py test -q
notifications:
    email: false
